"""empty message

Revision ID: 1aaa0695de86
Revises: c170afed8614
Create Date: 2020-04-28 20:51:23.319763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aaa0695de86'
down_revision = 'c170afed8614'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('east', sa.String(length=20), nullable=True))
    op.add_column('room', sa.Column('floor', sa.String(length=20), nullable=True))
    op.add_column('room', sa.Column('north', sa.String(length=20), nullable=True))
    op.add_column('room', sa.Column('south', sa.String(length=20), nullable=True))
    op.add_column('room', sa.Column('west', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'west')
    op.drop_column('room', 'south')
    op.drop_column('room', 'north')
    op.drop_column('room', 'floor')
    op.drop_column('room', 'east')
    # ### end Alembic commands ###
