"""empty message

Revision ID: 6494738c65b5
Revises: dcdb8774a414
Create Date: 2020-04-30 01:38:41.710201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6494738c65b5'
down_revision = 'dcdb8774a414'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('name', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'name')
    # ### end Alembic commands ###
