"""empty message

Revision ID: da0a6c09de9a
Revises: 0a6ec25cbea8
Create Date: 2020-04-30 09:31:18.905577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da0a6c09de9a'
down_revision = '0a6ec25cbea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('npc', sa.Column('ref', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'npc', ['ref'])
    op.add_column('room', sa.Column('mobs', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'mobs')
    op.drop_constraint(None, 'npc', type_='unique')
    op.drop_column('npc', 'ref')
    # ### end Alembic commands ###
