"""empty message

Revision ID: dcdb8774a414
Revises: c6a9b0d81d0d
Create Date: 2020-04-29 22:11:44.261456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcdb8774a414'
down_revision = 'c6a9b0d81d0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('NPC')
    op.add_column('users', sa.Column('items', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'items')
    op.create_table('NPC',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"NPC_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('items', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('gold', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('HP', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('isHostile', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('attack', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='NPC_pkey'),
    sa.UniqueConstraint('name', name='NPC_name_key')
    )
    # ### end Alembic commands ###
